name: faui_demo

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  faui:
    path: ..
  http: ^0.12.0+2
  crypted_preferences: ^0.0.2
  uuid: ^2.0.1
  url_launcher: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
