name: flutter_auth_ui

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_for_web: any
  flutter_for_web_ui: any
  html: ^0.14.0
  http: ^0.12.0+2
  uuid: ^2.0.1

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  test: any
